/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.hallock.tfe.dsktp.gui;

import org.hallock.tfe.client.ClientConnection;
import org.hallock.tfe.msg.ls.UpdatePlayer;
import org.hallock.tfe.serve.PlayerSpec;
import org.hallock.tfe.serve.WaitingPlayerInfo;

/**
 *
 * @author trever
 */
public class DesktopLobbyPlayerViewer extends javax.swing.JPanel {
    
	ClientConnection connection;
        WaitingPlayerInfo player;
    /**
     * Creates new form LobbyPlayer
 * @param isHost 
     */
    public DesktopLobbyPlayerViewer(WaitingPlayerInfo player, ClientConnection client, boolean isHost) {
        this.player = player;
        this.connection = client;
        initComponents();
        switch (player.type)
        {
            case HumanPlayer:
                jComboBox1.setSelectedIndex(0);
                break;
            case Computer:
                jComboBox1.setSelectedIndex(1);
                break;
            default:
                throw new RuntimeException("here");
        }
        statusLabel.setText(player.status);
        this.infoLabel.setText(player.name);
        jComboBox1.setEnabled(!player.isHost && isHost);
        jButton1.setEnabled(!player.isHost && isHost && player.type.equals(PlayerSpec.HumanPlayer));
    }

/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        jButton1.setText("Kick");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
	public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Type:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Human Player", "Computer Player" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            @Override
	public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Info:");

        infoLabel.setText("loading...");

        jLabel4.setText("Status:");

        statusLabel.setText("loading...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(infoLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel4)
                        .addComponent(statusLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
		UpdatePlayer.UpdateAction action = null;

		PlayerSpec selectedSpec = getSelectedSpec();
		if (player.type.equals(selectedSpec))
			return;

		switch (selectedSpec)
		{
		case HumanPlayer:
			action = UpdatePlayer.UpdateAction.SetHuman;
			break;
		case Computer:
			action = UpdatePlayer.UpdateAction.SetComputer;
			break;
		default:
			throw new RuntimeException("uh oh");
		}

		connection.sendUpdatePlayer(player, action);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

		connection.sendUpdatePlayer(player, UpdatePlayer.UpdateAction.Kick);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
    
    
	private PlayerSpec getSelectedSpec()
	{
		switch (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()))
		{
		case "Human Player":
			return PlayerSpec.HumanPlayer;
		case "Computer Player":
			return PlayerSpec.Computer;
		default:
			throw new RuntimeException("This option is not implemented");
		}
	}

	private void update()
	{
		switch (getSelectedSpec())
		{
		case HumanPlayer:
			break;
		case Computer:
			infoLabel.setText("The AI");
			statusLabel.setText("Ready");
			break;
		default:
			throw new RuntimeException("This option is not implemented");
		}
		// do something to somethingToChangeTheOptions
	}
}
